### ISSUE TITLE
GPU accelerated viz library?

### ISSUE THREAD

**Issue by davidrpugh** [kaust-vislab/nvidia-rapids-data-science-project#3]
I would like to include a good GPU accelerated viz package in the environment. [DataShader](http://datashader.org/) looks to be a good candidate as they will be [supporting RAPIDS within the next year (or so)](https://github.com/pyviz/datashader/issues/132).

I wonder if I should go ahead and add DataShader now?

**Comment by jbednar** [comment]
NVIDIA GPU support is now in Datashader (version 0.9.0); see https://github.com/holoviz/datashader/pull/793 .

**Comment by davidrpugh** [comment]
@jbednar Thanks for pointing this out! I have merged support for Datashader into the environment file.
